[package]
name = "cauliflambda"
version = "0.1.0"
edition = "2021"

[dependencies]
trait-set = "0.3.0"
unicode-xid = "0.2.4"
winnow = "0.4.6"
fmtastic = { version = "0.1.0" }

[workspace]
members = [
    "crates/cauliflambda-bin"
]
